Error shows that the filename doesnâ€™t exist , so checked the file in the directory was myfile. Hence edited the code 
with open('myfile.txt','r') as f: and it worked . 